// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tips.Purchase.Api.Entities;

#nullable disable

namespace Tips.Purchase.Api.Migrations
{
    [DbContext(typeof(TipsPurchaseDbContext))]
    [Migration("20230221101305_rfqfinal")]
    partial class rfqfinal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Tips.Purchase.Api.Entities.DocumentUpload", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocumentFrom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("ParentNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PurchaseOrderId")
                        .HasColumnType("int");

                    b.Property<int?>("PurchaseRequisitionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PurchaseOrderId");

                    b.HasIndex("PurchaseRequisitionId");

                    b.ToTable("DocumentUploads");
                });

            modelBuilder.Entity("Tips.Purchase.Api.Entities.PRDocumentUpload", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocumentFrom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("ParentNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PurchaseRequisitionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PurchaseRequisitionId");

                    b.ToTable("PRDocumentUploads");
                });

            modelBuilder.Entity("Tips.Purchase.Api.Entities.PoAddDeliverySchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("PODeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PODeliveryQty")
                        .HasPrecision(13, 3)
                        .HasColumnType("decimal(13,3)");

                    b.Property<int>("POItemDetailId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("POItemDetailId");

                    b.ToTable("PoAddDeliverySchedules");
                });

            modelBuilder.Entity("Tips.Purchase.Api.Entities.PoAddProject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("POItemDetailId")
                        .HasColumnType("int");

                    b.Property<string>("ProjectNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ProjectQty")
                        .HasPrecision(13, 3)
                        .HasColumnType("decimal(13,3)");

                    b.HasKey("Id");

                    b.HasIndex("POItemDetailId");

                    b.ToTable("PoAddProjects");
                });

            modelBuilder.Entity("Tips.Purchase.Api.Entities.PoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BalanceQty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CGST")
                        .HasPrecision(13, 3)
                        .HasColumnType("decimal(13,3)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("IGST")
                        .HasPrecision(13, 3)
                        .HasColumnType("decimal(13,3)");

                    b.Property<bool>("IsTechnicalDocsRequired")
                        .HasColumnType("bit");

                    b.Property<string>("ItemNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("MftrItemNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PONumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PoPartsStatus")
                        .HasColumnType("bit");

                    b.Property<int>("PurchaseOrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Qty")
                        .HasPrecision(13, 3)
                        .HasColumnType("decimal(13,3)");

                    b.Property<decimal>("SGST")
                        .HasPrecision(13, 3)
                        .HasColumnType("decimal(13,3)");

                    b.Property<string>("SpecialInstruction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("SubTotal")
                        .HasPrecision(13, 3)
                        .HasColumnType("decimal(13,3)");

                    b.Property<decimal>("TotalWithTax")
                        .HasPrecision(13, 3)
                        .HasColumnType("decimal(13,3)");

                    b.Property<string>("UOM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("UTGST")
                        .HasPrecision(13, 3)
                        .HasColumnType("decimal(13,3)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.HasKey("Id");

                    b.HasIndex("PurchaseOrderId");

                    b.ToTable("PoItems");
                });

            modelBuilder.Entity("Tips.Purchase.Api.Entities.PrAddDeliverySchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("PrDeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PrDeliveryQty")
                        .HasPrecision(13, 3)
                        .HasColumnType("decimal(13,3)");

                    b.Property<int>("PrItemDetailId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PrItemDetailId");

                    b.ToTable("PrAddDeliverySchedules");
                });

            modelBuilder.Entity("Tips.Purchase.Api.Entities.PrAddProject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PrItemDetailId")
                        .HasColumnType("int");

                    b.Property<string>("ProjectNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ProjectQty")
                        .HasPrecision(13, 3)
                        .HasColumnType("decimal(13,3)");

                    b.HasKey("Id");

                    b.HasIndex("PrItemDetailId");

                    b.ToTable("PrAddProjects");
                });

            modelBuilder.Entity("Tips.Purchase.Api.Entities.PrItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("MftrItemNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PurchaseRequistionId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Qty")
                        .HasPrecision(13, 3)
                        .HasColumnType("decimal(13,3)");

                    b.Property<string>("SpecialInstruction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UOM")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PurchaseRequistionId");

                    b.ToTable("PrItems");
                });

            modelBuilder.Entity("Tips.Purchase.Api.Entities.PurchaseOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BillTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeliveryTerms")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsShortClosed")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("POApprovalI")
                        .HasColumnType("bit");

                    b.Property<bool>("POApprovalII")
                        .HasColumnType("bit");

                    b.Property<string>("POApprovedIBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("POApprovedIDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("POApprovedIIBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("POApprovedIIDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PODate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PONumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentTerms")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProcurementType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("QuotationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("QuotationReferenceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RetentionPeriod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RevisionNumber")
                        .HasColumnType("int");

                    b.Property<string>("ShipTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShippingMode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortClosedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ShortClosedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("SpecialTermsAndConditions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Unit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VendorAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VendorId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VendorName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PurchaseOrders");
                });

            modelBuilder.Entity("Tips.Purchase.Api.Entities.PurchaseRequisition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BillTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeliveryTerms")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsShortClosed")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentTerms")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PrApprovalI")
                        .HasColumnType("bit");

                    b.Property<bool>("PrApprovalII")
                        .HasColumnType("bit");

                    b.Property<string>("PrApprovedIBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PrApprovedIDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PrApprovedIIBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PrApprovedIIDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PrDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PrNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProcurementType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Purpose")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RetentionPeriod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RevisionNumber")
                        .HasColumnType("int");

                    b.Property<string>("ShipTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShippingMode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortClosedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ShortClosedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("SpecialTermsConditions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PurchaseRequisitions");
                });

            modelBuilder.Entity("Tips.Purchase.Api.Entities.DocumentUpload", b =>
                {
                    b.HasOne("Tips.Purchase.Api.Entities.PurchaseOrder", "PurchaseOrder")
                        .WithMany("POFiles")
                        .HasForeignKey("PurchaseOrderId");

                    b.HasOne("Tips.Purchase.Api.Entities.PurchaseRequisition", "PurchaseRequisition")
                        .WithMany()
                        .HasForeignKey("PurchaseRequisitionId");

                    b.Navigation("PurchaseOrder");

                    b.Navigation("PurchaseRequisition");
                });

            modelBuilder.Entity("Tips.Purchase.Api.Entities.PRDocumentUpload", b =>
                {
                    b.HasOne("Tips.Purchase.Api.Entities.PurchaseRequisition", "PurchaseRequisition")
                        .WithMany("PrFiles")
                        .HasForeignKey("PurchaseRequisitionId");

                    b.Navigation("PurchaseRequisition");
                });

            modelBuilder.Entity("Tips.Purchase.Api.Entities.PoAddDeliverySchedule", b =>
                {
                    b.HasOne("Tips.Purchase.Api.Entities.PoItem", "POItemDetail")
                        .WithMany("POAddDeliverySchedules")
                        .HasForeignKey("POItemDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("POItemDetail");
                });

            modelBuilder.Entity("Tips.Purchase.Api.Entities.PoAddProject", b =>
                {
                    b.HasOne("Tips.Purchase.Api.Entities.PoItem", "POItemDetail")
                        .WithMany("POAddprojects")
                        .HasForeignKey("POItemDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("POItemDetail");
                });

            modelBuilder.Entity("Tips.Purchase.Api.Entities.PoItem", b =>
                {
                    b.HasOne("Tips.Purchase.Api.Entities.PurchaseOrder", "PurchaseOrder")
                        .WithMany("POItemList")
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PurchaseOrder");
                });

            modelBuilder.Entity("Tips.Purchase.Api.Entities.PrAddDeliverySchedule", b =>
                {
                    b.HasOne("Tips.Purchase.Api.Entities.PrItem", "PrItemDetail")
                        .WithMany("PrAddDeliverySchedules")
                        .HasForeignKey("PrItemDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrItemDetail");
                });

            modelBuilder.Entity("Tips.Purchase.Api.Entities.PrAddProject", b =>
                {
                    b.HasOne("Tips.Purchase.Api.Entities.PrItem", "PrItemDetail")
                        .WithMany("PrAddprojects")
                        .HasForeignKey("PrItemDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrItemDetail");
                });

            modelBuilder.Entity("Tips.Purchase.Api.Entities.PrItem", b =>
                {
                    b.HasOne("Tips.Purchase.Api.Entities.PurchaseRequisition", "PurchaseRequistion")
                        .WithMany("PrItemList")
                        .HasForeignKey("PurchaseRequistionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PurchaseRequistion");
                });

            modelBuilder.Entity("Tips.Purchase.Api.Entities.PoItem", b =>
                {
                    b.Navigation("POAddDeliverySchedules");

                    b.Navigation("POAddprojects");
                });

            modelBuilder.Entity("Tips.Purchase.Api.Entities.PrItem", b =>
                {
                    b.Navigation("PrAddDeliverySchedules");

                    b.Navigation("PrAddprojects");
                });

            modelBuilder.Entity("Tips.Purchase.Api.Entities.PurchaseOrder", b =>
                {
                    b.Navigation("POFiles");

                    b.Navigation("POItemList");
                });

            modelBuilder.Entity("Tips.Purchase.Api.Entities.PurchaseRequisition", b =>
                {
                    b.Navigation("PrFiles");

                    b.Navigation("PrItemList");
                });
#pragma warning restore 612, 618
        }
    }
}
