// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tips.SalesService.Api.Entities;

#nullable disable

namespace Tips.SalesService.Api.Migrations
{
    [DbContext(typeof(TipsSalesServiceDbContext))]
    [Migration("20221109105241_rfqfinal")]
    partial class rfqfinal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Tips.SalesService.Api.Entities.Rfq", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerRfqNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("QuoteExpectDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RequestReceiveDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RfqNumbers")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("rfqs");
                });

            modelBuilder.Entity("Tips.SalesService.Api.Entities.RfqNumber", b =>
                {
                    b.Property<int>("RfqNO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RfqNO"));

                    b.HasKey("RfqNO");

                    b.ToTable("rfqNumbers");
                });
#pragma warning restore 612, 618
        }
    }
}
