// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tips.SalesService.Api.Entities;

#nullable disable

namespace Tips.SalesService.Api.Migrations
{
    [DbContext(typeof(TipsSalesServiceDbContext))]
    partial class TipsSalesServiceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Tips.SalesService.Api.Entities.Rfq", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerRfqNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("QuoteExpectdate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RequestReceivedate")
                        .HasColumnType("datetime2");

                    b.Property<float?>("RevNumber")
                        .HasColumnType("real");

                    b.Property<int>("RfqNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("rfqs");
                });

            modelBuilder.Entity("Tips.SalesService.Api.Entities.RfqCustomFields", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CustomFieldSchedule")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LabelName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaxLengthUnit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("RfqId")
                        .HasColumnType("int");

                    b.Property<int>("RfqNumber")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ScheduleDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ScheduleQuantity")
                        .HasColumnType("int");

                    b.Property<string>("SelectCustomGroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SelectCustomGroups")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RfqId");

                    b.ToTable("rfqCustomFields");
                });

            modelBuilder.Entity("Tips.SalesService.Api.Entities.RfqCustomGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomGroupName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RfqId")
                        .HasColumnType("int");

                    b.Property<int>("RfqNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RfqId");

                    b.ToTable("rfqCustomGroups");
                });

            modelBuilder.Entity("Tips.SalesService.Api.Entities.RfqEngineering", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("EnggCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnggNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemMaster")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RfqId")
                        .HasColumnType("int");

                    b.Property<int>("RfqNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RfqId");

                    b.ToTable("rfqEngineerings");
                });

            modelBuilder.Entity("Tips.SalesService.Api.Entities.RfqNumber", b =>
                {
                    b.Property<int>("RfqNO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RfqNO"));

                    b.HasKey("RfqNO");

                    b.ToTable("rfqNumbers");
                });

            modelBuilder.Entity("Tips.SalesService.Api.Entities.RfqCustomFields", b =>
                {
                    b.HasOne("Tips.SalesService.Api.Entities.Rfq", "Rfq")
                        .WithMany("RfqCustomFields")
                        .HasForeignKey("RfqId");

                    b.Navigation("Rfq");
                });

            modelBuilder.Entity("Tips.SalesService.Api.Entities.RfqCustomGroup", b =>
                {
                    b.HasOne("Tips.SalesService.Api.Entities.Rfq", "Rfq")
                        .WithMany("RfqCustomGroups")
                        .HasForeignKey("RfqId");

                    b.Navigation("Rfq");
                });

            modelBuilder.Entity("Tips.SalesService.Api.Entities.RfqEngineering", b =>
                {
                    b.HasOne("Tips.SalesService.Api.Entities.Rfq", "Rfq")
                        .WithMany("RfqEngineerings")
                        .HasForeignKey("RfqId");

                    b.Navigation("Rfq");
                });

            modelBuilder.Entity("Tips.SalesService.Api.Entities.Rfq", b =>
                {
                    b.Navigation("RfqCustomFields");

                    b.Navigation("RfqCustomGroups");

                    b.Navigation("RfqEngineerings");
                });
#pragma warning restore 612, 618
        }
    }
}
