// <auto-generated />
using System;
using Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Entities.Migrations
{
    [DbContext(typeof(TipsMasterDbContext))]
    partial class TipsMasterDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Entities.Bank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("BankName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Banks");
                });

            modelBuilder.Entity("Entities.BasicOfApproval", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("BasicOfApprovalName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BasicOfApprovals");
                });

            modelBuilder.Entity("Entities.Commodity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("ActiveStatus")
                        .HasColumnType("bit");

                    b.Property<string>("CommodityType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Commodity");
                });

            modelBuilder.Entity("Entities.CompanyAddresses", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int?>("CompanyMasterId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("GSTNNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("PANNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PoAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SameasAddress")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CompanyMasterId");

                    b.ToTable("CompanyAddresses");
                });

            modelBuilder.Entity("Entities.CompanyBanking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AccountNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Branch")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int?>("CompanyMasterId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("IBANCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IFSCCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Primary")
                        .HasColumnType("bit");

                    b.Property<string>("SwiftCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyMasterId");

                    b.ToTable("CompanyBankings");
                });

            modelBuilder.Entity("Entities.CompanyContacts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AlternameMobileNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CallName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int?>("CompanyMasterId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Designation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Extension")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LandLine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Language")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Primary")
                        .HasColumnType("bit");

                    b.Property<string>("Salutation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimeToCall")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyMasterId");

                    b.ToTable("CompanyContacts");
                });

            modelBuilder.Entity("Entities.CompanyMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("AS")
                        .HasColumnType("bit");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Advance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApprovalBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ApprovalDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ApprovalStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuditFrequency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BasisOfApproval")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BoardNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Capacity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyAliasName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DNBHooversNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ERP")
                        .HasColumnType("bit");

                    b.Property<string>("ERPvalue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ESDSetup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExportUnitType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FloorSpace")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("GST")
                        .HasColumnType("bit");

                    b.Property<string>("GeneralEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("GeneralMSME")
                        .HasColumnType("bit");

                    b.Property<string>("GooglePinLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HazmatSetup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeadCount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ICRA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IEC")
                        .HasColumnType("bit");

                    b.Property<bool>("ISO")
                        .HasColumnType("bit");

                    b.Property<bool>("InCoporation")
                        .HasColumnType("bit");

                    b.Property<string>("IncoTerm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("InventoryItem")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("MSME")
                        .HasColumnType("bit");

                    b.Property<string>("Machine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Medical")
                        .HasColumnType("bit");

                    b.Property<bool>("NADCAP")
                        .HasColumnType("bit");

                    b.Property<string>("NatureOfRelationship")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("OSP")
                        .HasColumnType("bit");

                    b.Property<string>("OSPvalue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PAN")
                        .HasColumnType("bit");

                    b.Property<string>("PaymentTerms")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PinZipCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreferredFreightForwader")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PurchaseGroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ReAudit")
                        .HasColumnType("bit");

                    b.Property<string>("RelatedCompanyAlias")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RelatedCompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScopeOfSupply")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecialTerms")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TIN")
                        .HasColumnType("bit");

                    b.Property<string>("ToolsandEquip")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TurnOver3years")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeOfCompany")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UOM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("UdhyamCertificate")
                        .HasColumnType("bit");

                    b.Property<string>("Upload")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sqft")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CompanyMasters");
                });

            modelBuilder.Entity("Entities.Currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrencyNames")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Currencies");
                });

            modelBuilder.Entity("Entities.CustomerAddresses", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int?>("CustomerMasterId")
                        .HasColumnType("int");

                    b.Property<string>("GSTNNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvoiceAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("PANNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerMasterId");

                    b.ToTable("CustomerAddresses");
                });

            modelBuilder.Entity("Entities.CustomerBanking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AccountNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Branch")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int?>("CustomerMasterId")
                        .HasColumnType("int");

                    b.Property<string>("IBANCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IFSCCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Primary")
                        .HasColumnType("bit");

                    b.Property<string>("SwiftCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerMasterId");

                    b.ToTable("CustomerBankings");
                });

            modelBuilder.Entity("Entities.CustomerContacts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AlternameMobileNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CallName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int?>("CustomerMasterId")
                        .HasColumnType("int");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Designation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Extension")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LandLine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Language")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Primary")
                        .HasColumnType("bit");

                    b.Property<string>("Salutation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimeToCall")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerMasterId");

                    b.ToTable("CustomerContacts");
                });

            modelBuilder.Entity("Entities.CustomerMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Advance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApprovalBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ApprovalDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AuditFrequency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BasisOfApproval")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BoardNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Capacity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerAliasName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DNBNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DropShipment")
                        .HasColumnType("bit");

                    b.Property<bool>("ERP")
                        .HasColumnType("bit");

                    b.Property<bool>("ERPDetails")
                        .HasColumnType("bit");

                    b.Property<string>("ERPValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ESDSetup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ESDSetupDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Equip")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EquipDetials")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExportUnitType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FloorSpace")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("GST")
                        .HasColumnType("bit");

                    b.Property<string>("GeneralEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("GeneralMSME")
                        .HasColumnType("bit");

                    b.Property<string>("GooglePinLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HazmatSetup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HazmatSetupDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeadCount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ICRA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IEC")
                        .HasColumnType("bit");

                    b.Property<string>("INCOTerms")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Incorporation")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("LDApplicable")
                        .HasColumnType("bit");

                    b.Property<string>("LDApplicableValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("MSME")
                        .HasColumnType("bit");

                    b.Property<string>("Machine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MachineDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NatureOfRelationship")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("OSP")
                        .HasColumnType("bit");

                    b.Property<string>("OSPValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PAN")
                        .HasColumnType("bit");

                    b.Property<bool>("PODReq")
                        .HasColumnType("bit");

                    b.Property<string>("PackingInstructions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PartialDispatch")
                        .HasColumnType("bit");

                    b.Property<string>("PaymentTerms")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PinZipCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreferredFreightForwarder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ReAudit")
                        .HasColumnType("bit");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RelatedCustomerAlias")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RelatedCustomerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SalesManager")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScopeOfSupply")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Segment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShipmentInstructions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SourceInspection")
                        .HasColumnType("bit");

                    b.Property<string>("SourceInspectionValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecialInstructions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecialTerms")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sqft")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TIN")
                        .HasColumnType("bit");

                    b.Property<string>("Tools")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToolsDetials")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TurnOver")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeOfCompany")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UOM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("UdhyamCertificate")
                        .HasColumnType("bit");

                    b.Property<string>("Upload")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CustomerMasters");
                });

            modelBuilder.Entity("Entities.CustomerShippingAddresses", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int?>("CustomerMasterId")
                        .HasColumnType("int");

                    b.Property<string>("GSTNNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GooglePinLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("SameasAddress")
                        .HasColumnType("bit");

                    b.Property<string>("ShippingAddress")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerMasterId");

                    b.ToTable("CustomerShippingAddresses");
                });

            modelBuilder.Entity("Entities.CustomerType", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"), 1L, 1);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CustomerTypes");
                });

            modelBuilder.Entity("Entities.DeliveryTerm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeliveryTermName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DeliveryTerms");
                });

            modelBuilder.Entity("Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("DepartmentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("Entities.IncoTerm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IncoTermName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("IncoTerms");
                });

            modelBuilder.Entity("Entities.ItemMaster", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("BatchSize")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Commodity")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CostCenter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CostingMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerPartReference")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Department")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Depreciation")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DocRet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DrawingNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Expiry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FootPrint")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GrProcessing")
                        .HasColumnType("int");

                    b.Property<string>("GrossUom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("GrossWeight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Hsn")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("InspectionInterval")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCocRequired")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCustomerSuppliedItem")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCycleCount")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEsd")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFifo")
                        .HasColumnType("bit");

                    b.Property<bool>("IsHazardousMaterial")
                        .HasColumnType("bit");

                    b.Property<bool>("IsIQCRequired")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLifo")
                        .HasColumnType("bit");

                    b.Property<bool>("IsObsolete")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPRRequired")
                        .HasColumnType("bit");

                    b.Property<bool>("IsReachItem")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRohsItem")
                        .HasColumnType("bit");

                    b.Property<bool>("IsShelfLife")
                        .HasColumnType("bit");

                    b.Property<string>("ItemNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ItemType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Kanban")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Leadtime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaterialGroup")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Max")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Min")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NetUom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("NetWeight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("OpenGrin")
                        .HasColumnType("bit");

                    b.Property<bool>("Pfo")
                        .HasColumnType("bit");

                    b.Property<string>("PoMaterialType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PurchaseGroup")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Reorder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RevNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShippingInstruction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Size")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SpecialInstructions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("StdCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TwoBin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Uom")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ValidTo")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Valuation")
                        .HasColumnType("bit");

                    b.Property<decimal>("Volume")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("VolumeUom")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ItemMasters");
                });

            modelBuilder.Entity("Entities.ItemmasterAlternate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<long>("ItemMasterId")
                        .HasColumnType("bigint");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManufacturerPartNo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ItemMasterId");

                    b.ToTable("ItemmasterAlternate");
                });

            modelBuilder.Entity("Entities.ItemMasterApprovedVendor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<long>("ItemMasterId")
                        .HasColumnType("bigint");

                    b.Property<string>("ShareOfBusiness")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VendorCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VendorName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ItemMasterId");

                    b.ToTable("ItemMasterApprovedVendor");
                });

            modelBuilder.Entity("Entities.ItemMasterFileUpload", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ItemMasterId")
                        .HasColumnType("bigint");

                    b.Property<string>("UploadedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UploadedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ItemMasterId");

                    b.ToTable("ItemMasterFileUpload");
                });

            modelBuilder.Entity("Entities.ItemMasterRouting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("IsRoutingActive")
                        .HasColumnType("bit");

                    b.Property<long>("ItemMasterId")
                        .HasColumnType("bigint");

                    b.Property<string>("LaborHours")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MachineHours")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Process")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProcessStep")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoutingDescription")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ItemMasterId");

                    b.ToTable("ItemMasterRouting");
                });

            modelBuilder.Entity("Entities.ItemMasterWarehouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<long>("ItemMasterId")
                        .HasColumnType("bigint");

                    b.Property<string>("WareHouse")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ItemMasterId");

                    b.ToTable("ItemMasterWarehouse");
                });

            modelBuilder.Entity("Entities.LeadTime", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"), 1L, 1);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Days")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Weeks")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LeadTimes");
                });

            modelBuilder.Entity("Entities.Locations", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("ActiveStatus")
                        .HasColumnType("bit");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("Entities.MaterialType", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"), 1L, 1);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaterialTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MaterialTypes");
                });

            modelBuilder.Entity("Entities.ProcurementType", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"), 1L, 1);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProcurementName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProcurementTypes");
                });

            modelBuilder.Entity("Entities.ScopeOfSupply", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScopeOfSupplyName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ScopeOfSupplies");
                });

            modelBuilder.Entity("Entities.UOC", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("ActiveStatus")
                        .HasColumnType("bit");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UOCType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Uoc");
                });

            modelBuilder.Entity("Entities.UOM", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("ActiveStatus")
                        .HasColumnType("bit");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UOMName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Uom");
                });

            modelBuilder.Entity("Entities.VendorAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("GSTNNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("PANNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PoAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SameasAddress")
                        .HasColumnType("bit");

                    b.Property<int>("VendorId")
                        .HasColumnType("int");

                    b.Property<int?>("VendorMasterId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VendorMasterId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("Entities.VendorBanking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AccountNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Branch")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("IBANCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IFSCCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Primary")
                        .HasColumnType("bit");

                    b.Property<string>("SwiftCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VendorId")
                        .HasColumnType("int");

                    b.Property<int?>("VendorMasterId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VendorMasterId");

                    b.ToTable("VendorBankings");
                });

            modelBuilder.Entity("Entities.VendorCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VendorCategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("VendorCategories");
                });

            modelBuilder.Entity("Entities.VendorContacts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AlternameMobileNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CallName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Designation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Extension")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LandLine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Language")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Primary")
                        .HasColumnType("bit");

                    b.Property<string>("Salutation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimeToCall")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VendorId")
                        .HasColumnType("int");

                    b.Property<int?>("VendorMasterId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VendorMasterId");

                    b.ToTable("Contact");
                });

            modelBuilder.Entity("Entities.VendorDepartment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VendorDepartmentName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("VendorDepartments");
                });

            modelBuilder.Entity("Entities.VendorMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("AS")
                        .HasColumnType("bit");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApprovalBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ApprovalDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ApprovalStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuditFrequency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankOfApproval")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BoardNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Capacity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DNBHooversNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ERP")
                        .HasColumnType("bit");

                    b.Property<string>("ERPvalue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ESDSetup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExportUnitType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FloorSpace")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("GST")
                        .HasColumnType("bit");

                    b.Property<string>("GeneralEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("GeneralMSME")
                        .HasColumnType("bit");

                    b.Property<string>("GooglePinLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HazmatSetup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeadCount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ICRA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IEC")
                        .HasColumnType("bit");

                    b.Property<bool>("ISO")
                        .HasColumnType("bit");

                    b.Property<bool>("InCoporation")
                        .HasColumnType("bit");

                    b.Property<string>("IncoTerm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("InventoryItem")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("MSME")
                        .HasColumnType("bit");

                    b.Property<string>("Machine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Medical")
                        .HasColumnType("bit");

                    b.Property<bool>("NADCAP")
                        .HasColumnType("bit");

                    b.Property<string>("NatureOfRelationship")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("OSP")
                        .HasColumnType("bit");

                    b.Property<string>("OSPvalue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PAN")
                        .HasColumnType("bit");

                    b.Property<string>("PaymentTerms")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PinZipCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreferredFreightForwader")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PurchaseGroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ReAudit")
                        .HasColumnType("bit");

                    b.Property<string>("RelatedVendorAlias")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RelatedVendorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScopeOfSupply")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecialTerms")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TIN")
                        .HasColumnType("bit");

                    b.Property<string>("TermAdvance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToolsandEquip")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TurnOver3years")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeOfCompany")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UOM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("UdhyamCertificate")
                        .HasColumnType("bit");

                    b.Property<string>("Upload")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VendorAliasName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VendorCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VendorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VendorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VendorType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sqft")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("VendorMasters");
                });

            modelBuilder.Entity("Entities.VolumeUom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VolumeUomName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("VolumeUoms");
                });

            modelBuilder.Entity("Entities.WeightUom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WeightUomName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WeightUoms");
                });

            modelBuilder.Entity("Entities.CompanyAddresses", b =>
                {
                    b.HasOne("Entities.CompanyMaster", "CompanyMaster")
                        .WithMany("CompanyAddresses")
                        .HasForeignKey("CompanyMasterId");

                    b.Navigation("CompanyMaster");
                });

            modelBuilder.Entity("Entities.CompanyBanking", b =>
                {
                    b.HasOne("Entities.CompanyMaster", "CompanyMaster")
                        .WithMany("CompanyBankings")
                        .HasForeignKey("CompanyMasterId");

                    b.Navigation("CompanyMaster");
                });

            modelBuilder.Entity("Entities.CompanyContacts", b =>
                {
                    b.HasOne("Entities.CompanyMaster", "CompanyMaster")
                        .WithMany("CompanyContacts")
                        .HasForeignKey("CompanyMasterId");

                    b.Navigation("CompanyMaster");
                });

            modelBuilder.Entity("Entities.CustomerAddresses", b =>
                {
                    b.HasOne("Entities.CustomerMaster", "CustomerMaster")
                        .WithMany("CustomerAddresses")
                        .HasForeignKey("CustomerMasterId");

                    b.Navigation("CustomerMaster");
                });

            modelBuilder.Entity("Entities.CustomerBanking", b =>
                {
                    b.HasOne("Entities.CustomerMaster", "CustomerMaster")
                        .WithMany("CustomerBanking")
                        .HasForeignKey("CustomerMasterId");

                    b.Navigation("CustomerMaster");
                });

            modelBuilder.Entity("Entities.CustomerContacts", b =>
                {
                    b.HasOne("Entities.CustomerMaster", "CustomerMaster")
                        .WithMany("CustomerContacts")
                        .HasForeignKey("CustomerMasterId");

                    b.Navigation("CustomerMaster");
                });

            modelBuilder.Entity("Entities.CustomerShippingAddresses", b =>
                {
                    b.HasOne("Entities.CustomerMaster", "CustomerMaster")
                        .WithMany("CustomerShippingAddresses")
                        .HasForeignKey("CustomerMasterId");

                    b.Navigation("CustomerMaster");
                });

            modelBuilder.Entity("Entities.ItemmasterAlternate", b =>
                {
                    b.HasOne("Entities.ItemMaster", "ItemMaster")
                        .WithMany("ItemmasterAlternate")
                        .HasForeignKey("ItemMasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemMaster");
                });

            modelBuilder.Entity("Entities.ItemMasterApprovedVendor", b =>
                {
                    b.HasOne("Entities.ItemMaster", "ItemMaster")
                        .WithMany("ItemMasterApprovedVendor")
                        .HasForeignKey("ItemMasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemMaster");
                });

            modelBuilder.Entity("Entities.ItemMasterFileUpload", b =>
                {
                    b.HasOne("Entities.ItemMaster", "ItemMaster")
                        .WithMany("ItemMasterFileUpload")
                        .HasForeignKey("ItemMasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemMaster");
                });

            modelBuilder.Entity("Entities.ItemMasterRouting", b =>
                {
                    b.HasOne("Entities.ItemMaster", "ItemMaster")
                        .WithMany("ItemMasterRouting")
                        .HasForeignKey("ItemMasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemMaster");
                });

            modelBuilder.Entity("Entities.ItemMasterWarehouse", b =>
                {
                    b.HasOne("Entities.ItemMaster", "ItemMaster")
                        .WithMany("ItemMasterWarehouse")
                        .HasForeignKey("ItemMasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemMaster");
                });

            modelBuilder.Entity("Entities.VendorAddress", b =>
                {
                    b.HasOne("Entities.VendorMaster", "VendorMaster")
                        .WithMany("Addresses")
                        .HasForeignKey("VendorMasterId");

                    b.Navigation("VendorMaster");
                });

            modelBuilder.Entity("Entities.VendorBanking", b =>
                {
                    b.HasOne("Entities.VendorMaster", "VendorMaster")
                        .WithMany("VendorBankings")
                        .HasForeignKey("VendorMasterId");

                    b.Navigation("VendorMaster");
                });

            modelBuilder.Entity("Entities.VendorContacts", b =>
                {
                    b.HasOne("Entities.VendorMaster", "VendorMaster")
                        .WithMany("Contacts")
                        .HasForeignKey("VendorMasterId");

                    b.Navigation("VendorMaster");
                });

            modelBuilder.Entity("Entities.CompanyMaster", b =>
                {
                    b.Navigation("CompanyAddresses");

                    b.Navigation("CompanyBankings");

                    b.Navigation("CompanyContacts");
                });

            modelBuilder.Entity("Entities.CustomerMaster", b =>
                {
                    b.Navigation("CustomerAddresses");

                    b.Navigation("CustomerBanking");

                    b.Navigation("CustomerContacts");

                    b.Navigation("CustomerShippingAddresses");
                });

            modelBuilder.Entity("Entities.ItemMaster", b =>
                {
                    b.Navigation("ItemMasterApprovedVendor");

                    b.Navigation("ItemMasterFileUpload");

                    b.Navigation("ItemMasterRouting");

                    b.Navigation("ItemMasterWarehouse");

                    b.Navigation("ItemmasterAlternate");
                });

            modelBuilder.Entity("Entities.VendorMaster", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Contacts");

                    b.Navigation("VendorBankings");
                });
#pragma warning restore 612, 618
        }
    }
}
